<?php
 // module/ProjectTimer/view/projecttimer/projecttimer/index.phtml:
 $title = 'My projecttimers';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url('projecttimer', array('action'=>'add'));?>">Add a new project</a>
 </p>

 <table class="table">
 <tr>
     <th>project</th>
     <th>total hours</th>
     <th>start/stop</th>
 </tr>
 <?php foreach ($projecthashkey as $pid=>$projectname) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($projecthashkey[$pid]);?></td>
     <td><?php echo $this->escapeHtml($timesummary[$pid]);?></td>
     <td>
        <?php if ( $projectstatus[$pid]==1 ): ?>
         <a href="<?php echo $this->url('projecttimer',
             array('action'=>'stop', 'id' => $projecttimer->project_id));?>">Stop</a>
        <?php else: ?>
         <a href="<?php echo $this->url('projecttimer',
             array('action'=>'start', 'id' => $projecttimer->project_id));?>">Start</a>
        <?php endif ?>
     </td>
 </tr>
 <?php endforeach; ?>
</table>
